### ISSUE TITLE
Boxes resize are basically destroyed.

### ISSUE THREAD

**Issue by Crewdz** [Cover6/C6Site#4]
The menu on the homepage looks fine when not on a web server, however when I put it on our web server the boxes resized and got rid of the icons.

# **Before**
<img src="https://i.gyazo.com/fec6f2df9dc9fac6d5b789cf89201a63.png"/>

# **After**
<img src="https://i.gyazo.com/79cd984e66bd8c0000488348993ba1c9.png"/>

For more investigation, if you'd like to check the files out on the web server they're located here:
https://cover6.net/nsite/

**Comment by lexman02** [comment]
Fixed in https://github.com/Cover6/C6Site/commit/60202dfad6dead3c733bbb43984c98b5f144f448
